env:
  es6: true
  browser: true
  commonjs: true
  jest: true

extends: [
    "eslint:recommended",
    "plugin:react/recommended"
  ]

parser: "@babel/eslint-parser"

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 6
  sourceType: module
  arrowFunctions: true,
  blockBindings: true,
  classes: true,
  defaultParams: true,
  destructuring: true,
  forOf: true,
  generators: false,
  modules: true,
  objectLiteralComputedProperties: true,
  objectLiteralDuplicateProperties: false,
  objectLiteralShorthandMethods: true,
  objectLiteralShorthandProperties: true,
  restParams: true,
  spread: true,
  superInFunctions: true,
  templateStrings: true,
  jsx: true

plugins: ['react']

rules: {
    "react/jsx-uses-react": "error",
    "react/jsx-uses-vars": "error",
  }

settings:
  react:
    version: '16'
